### ISSUE TITLE
Rename `Create link`

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#104]
I wonder if this should be more explicit and be renamed to `Create symlink`. `Create link` makes me think it generates a link to that directory/file which I could share although `share link` is more logical.

**Comment by KKoukiou** [comment]
The dialog allows you to create symlink or hard link. Therefore I don't see how to title can be more specific.

**Comment by nisha2k21** [comment]
Hello! I'd like to work on this issue:)

**Comment by KKoukiou** [comment]
@nisha2k21 as you can see in the discussion above, there is not final decision if this is desired or not. Please talk with @jelly who reported this, or please fine another one.

**Comment by AliGates915** [comment]
Plz assign this to me.

**Comment by KKoukiou** [comment]
@AliGates915 see https://github.com/cockpit-project/cockpit-navigator/issues/104#issuecomment-1813946912

**Comment by AliGates915** [comment]
@jelly @KKoukiou I am not understand what's actually file name, Where the symlink problem creating

**Comment by KKoukiou** [comment]
> @jelly @KKoukiou I am not understand what's actually file name, Where the symlink problem creating

Please pick another issue, this is not a good starter one, as it's not having a clear description. https://github.com/cockpit-project/cockpit-navigator/issues/67 would be a good candidate for example!

**Comment by abhishekjain58** [comment]
I Want to work on the issue please assign the issue.

**Comment by VrajRP2004** [comment]
I like to work on this issues please assign me this issue

**Comment by jelly** [comment]
Let's keep the current UI as is.
