### ISSUE TITLE
Allow the user to specify the full path to a desired directory

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-files#116]
![4](https://github.com/KKoukiou/cockpit-navigator/assets/14921356/eca2bd5a-c639-46ee-8795-6f629ae77a54)

**Comment by khadar1020** [comment]
I would like to solve this issue can you please give me some more information @KKoukiou

**Comment by KKoukiou** [comment]
Hi @khadar1020 thanks for the interest. This issue needs design first, and our designer is over capacity. So please pick another one from the one maked with 'good first issue' label.
https://github.com/cockpit-project/cockpit-navigator/labels/good%20first%20issue

**Comment by jelly** [comment]
Update, the SPUR introduced a design:

A new edit path button is introduced:

![image6](https://github.com/cockpit-project/cockpit-files/assets/67428/23d85258-824b-4748-bd21-44d16874b919)

Clicking the edit path button makes the path editable:

![image7](https://github.com/cockpit-project/cockpit-files/assets/67428/27ec3227-5665-4c10-83c4-fa4f5a4b69f0)

> And when you click on the edit button, it switches the clickable breadcrumb pathbar to a UNIXy full path editor with a PatternFly inline edit pattern, like so:

> Ideally, it’d preselect the last fragment of the path or perhaps just has nothing preselected and has the curser at the end. (Someone could control-backspace to remove a fragment, I guess?)
