### ISSUE TITLE
Hovering over file/folder icon doesn't show the background

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-files#126]
When mouse cursor is around the icon:

![image](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/45c9bdec-8527-48f2-b318-abf762e1c585)

When mouse cursor is *over*  the icon:

![image](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/1da57304-610c-4980-91c8-cd1ddcfdad4b)

It makes it feel janky.

**Comment by garrett** [comment]
This is a regression; the background hovered last time I worked on Navigator. I can look into it.

**Comment by subhoghoshX** [comment]
When I checked it today, the background is broken differently. Digging down it looks this commit 527f8087052ddcfd11c7eb3fd2dcc1dcb22a10a4 changed it. And I honestly think it looks much better now :)

Before there was the gray background with an ugly shadow which vanished when hovering on the Icon but not around it, and an weird blue border when focused. It looks cleaner now IMO.

Here's a before and after comparison:

https://github.com/cockpit-project/cockpit-navigator/assets/108616679/65294f85-73d9-43dc-b6df-2f1ff3f7fd19

It seems some node_modules change affected it, so please remove it when checking out.

**Comment by jelly** [comment]
Hover is now implemented 
![image](https://github.com/cockpit-project/cockpit-files/assets/67428/b3f4e7ec-aabd-4ecd-b262-abe1213d4251)
