### ISSUE TITLE
Can't open large directories like /bin, /lib64 or my screenshots directory :P

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-files#137]

**Comment by jelly** [comment]
Does it just take a very long time or is there an error, the fslist1 PR should improve the loading of large directories.

**Comment by subhoghoshX** [comment]
> Does it just take a very long time or is there an error, the fslist1 PR should improve the loading of large directories.

I must have missed the notification. Yes it's one of those eternal loading, I tried it again and waited for 40 minutes and it's still loading. The error in the console is the usual "Adding file failed".
