### ISSUE TITLE
Fix the width of the sidebar

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-files#138]
In smaller screens (~1300px) the sidebar jumps quite a bit and shifts the files grid. Sometimes changing from 4 columns to 3 columns while clicking on a file/folder. I've accidentally opened the wrong directory many times because of folders jumping around.

**Comment by yasirjawed** [comment]
Can I solve this issue? i'll just require some information and for the rest i will make PR after it's done

**Comment by KKoukiou** [comment]
@yasirjawed please go ahead with asking your questions on our communication channel. https://cockpit-project.org/search.html#contact

**Comment by bEluga0000** [comment]
@subhoghoshX can give us some screeshot i am intrested to solve this

**Comment by subhoghoshX** [comment]
> @subhoghoshX can give us some screeshot i am intrested to solve this

[Screencast from 2023-12-19 10-51-26.webm](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/315319e7-6986-4c56-8275-bf6847650c8f)

**Comment by subhoghoshX** [comment]
> @subhoghoshX can give us some screeshot i am intrested to solve this

[Screencast from 2023-12-19 10-51-26.webm](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/64c08c04-d4b7-4963-9d16-b8f976282dbe)

**Comment by Krishnendu22** [comment]
Hi, I'm interested into solving this issue. Can i please  get some information?

**Comment by NKcool** [comment]
assign me this issue i can fix it

**Comment by garrett** [comment]
This will be fully solved by #506. (I've done some previous PRs to address this prior, which didn't completely fix it, but provided a path to it, such as #493.)

**Comment by allisonkarlitskaya** [comment]
I just checked it, and this indeed got fixed by #506.
