### ISSUE TITLE
Allow sorting on filesize as well

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#200]
Same as sorting on first/last modified allow on size by default on.

![Screenshot from 2024-01-24 10-15-44](https://github.com/cockpit-project/cockpit-navigator/assets/67428/21a11db2-77d9-478f-89d8-fbadce3dda80)

![image](https://github.com/cockpit-project/cockpit-navigator/assets/67428/23d94733-b61c-4222-89b2-daa6b94e5300)

A further enhancement is to add the Size column to the list based view so you can toggle between sorting from large to small or small to large.

**Comment by MahmoudHamdy02** [comment]
Should this be the same as nautilus? It sorts files by size, and then folders by number of items

**Comment by jelly** [comment]
> Should this be the same as nautilus? It sorts files by size, and then folders by number of items

I agree

**Comment by jelly** [comment]
Added in https://github.com/cockpit-project/cockpit-files/commit/15ee985e21905a342118d418b4e24018cacf112d
