### ISSUE TITLE
testCopyPaste flakes often

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-files#224]
This is starting to get on my nerves.

Example: https://cockpit-logs.us-east-1.linodeobjects.com/pull-223-20240130-092539-bfedb008-arch/log.html#3-1

**Comment by jelly** [comment]
Same! I've spotted that it flakes after `mkdir`:

```
        self.assertEqual(m.execute("head -n 1 /home/admin/newdir/newfile"), "test_text\n")
        b.click(".breadcrumb-button:nth-of-type(3)")

        # Copy/paste directory
        self.browser.wait_not_present(".pf-c-empty-state")
        m.execute("mkdir /home/admin/copyDir")
        b.click("[data-item='copyDir']")
```

So what is `b.click(".breadcrumb-button:nth-of-type(3)")` are we changing a directory, then creating a new directory while our `fslist1` is not yet "ready"?

**Comment by jelly** [comment]
Have not seen it flake after our fsinfo merge. Also nothing spotted in https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit-files
