### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#226]
Here's how the new icons would look:

![Navigator, with inline breadcrumbs](https://github.com/cockpit-project/cockpit-navigator/assets/10246/c6dda9be-86b9-4d84-9b0a-424ff3df2101)

Things that are changed:

1. Darker color (as they can be now, as they're not filled but outline based).
2. Basic mimetypes; including just those that are available and make sense for admins.
3. Using icon SVGs from ForkAwesome, which is a fork from FontAwesome. (PatternFly's icons are also forked from FontAwesome.)
4. Emblem for symlinks.

The icons should exist in one place and be referenced instead of being inline SVG. (Using inline SVG is not great for performance at the level of a thousand items, which some system directories have.)

**Comment by garrett** [comment]
Here's what the new icons look like (out of context):

![New icons(2)](https://github.com/cockpit-project/cockpit-navigator/assets/10246/d58b2c77-73db-47d2-a015-769ff9ac42cb)


They're from ForkAwesome filetype icons: https://forkaweso.me/Fork-Awesome/icons/#file-type

Here's the file with optimized SVGs: **[⬇ filetypes.zip](https://github.com/cockpit-project/cockpit-navigator/files/14100644/filetypes.zip)**

Screenshot crop from Nautilus:

![image](https://github.com/cockpit-project/cockpit-navigator/assets/10246/153629b7-77a4-4060-b539-04934a4abc4e)

(I've included audio and video too... why not? We can skip those though... the others are more important, really.)

The license for the icons is OFL 1.1 (which is compatible): https://forkaweso.me/Fork-Awesome/license/
Specifically: https://openfontlicense.org/

We're already using a fork of Font Awesome in PatternFly, also under the OFL.

---

We probably want to include them with an `<object>` tag, so the browser can cache and optimize their usage, and we can still manipulate them (to recolor them in light mode and also make them work in dark mode too). https://svgontheweb.com/

Summary of that page on usage:

  | Object | Inline | Img | Background-image
-- | -- | -- | -- | --
CSS Manipulation | Yes | Yes | Some inline | Some inline
JS Manipulation | Yes | Yes | No | No
SVG Animation | Yes | Yes | Yes | Yes
Interactive SVG Animation | Yes | Yes | No | No

Object wins out. It looks like this:

```html
<object type="image/svg+xml" data="image.svg"></object>
```

I'll include the ones we should use, but I'll make sure they're optimized.

Although, since these are basically outlines, I think we could also do clip-path with the SVGs too, which would let us handle it in pure CSS, and that would _probably_ scale pretty well too. We could even make a single file with all of them, have an ID and use the clip-path specified by that ID. Or just use individual files. Or copy the path object out of the SVG and use it within the CSS with `clip-path: path('');` — but that'd probably require hardcoding the size and scaling it in Inkscape for each.

**Comment by garrett** [comment]
The link badge is PatternFly's `fa-arrow-circle-up` icon. (The "FA" mean FontAwesome, BTW.) It's been rotated to the right by 45° (which we can do with CSS) and placed in the top-right of the area (which we can do with `position: absolute`). It'd probably also need a pass-through with `pointer-events: none`.

**Comment by jelly** [comment]
From the File size sorting PR:

> But what about the filetype sorting? Do we replicate nautilus behavior of showing the biggest (or smallest) files first and then folders?

Sorting by type is:

1. Folders first (Type: Folder)
2. General type alphanumeric (Archive for zip, tgz, bz2, etc.; Document for PDF, ODT, etc.; Image for PNG, JPEG, etc.)
3. Extension sorting, A-Z
4. Base filename sorting, A-Z

That's what Nautilus does, and it makes sense.

Nautilus has the mapping of types @ https://gitlab.gnome.org/GNOME/nautilus/-/blob/main/src/nautilus-mime-actions.c#L100-259

<details>
<summary>Here's the same thing in a JSON object</summary>

```json
{
    "Files": [
        "application/octet-stream",
        "text/plain",
        "text/markdown"
    ],
    "Folders": [
        "inode/directory"
    ],
    "Documents": [
        "application/rtf",
        "application/msword",
        "application/vnd.sun.xml.writer",
        "application/vnd.sun.xml.writer.global",
        "application/vnd.sun.xml.writer.template",
        "application/vnd.oasis.opendocument.text",
        "application/vnd.oasis.opendocument.text-template",
        "application/x-abiword",
        "application/x-applix-word",
        "application/x-mswrite",
        "application/docbook+xml",
        "application/x-kword",
        "application/x-kword-crypt",
        "application/x-lyx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "text/markdown"
    ],
    "Illustration": [
        "application/illustrator",
        "application/vnd.corel-draw",
        "application/vnd.stardivision.draw",
        "application/vnd.oasis.opendocument.graphics",
        "application/x-dia-diagram",
        "application/x-karbon",
        "application/x-killustrator",
        "application/x-kivio",
        "application/x-kontour",
        "application/x-wpg"
    ],
    "Music": [
        "application/ogg",
        "audio/x-vorbis+ogg",
        "audio/ac3",
        "audio/basic",
        "audio/midi",
        "audio/x-flac",
        "audio/mp4",
        "audio/mpeg",
        "audio/x-mpeg",
        "audio/x-ms-asx",
        "audio/x-pn-realaudio"
    ],
    "PDF / PostScript": [
        "application/pdf",
        "application/postscript",
        "application/x-dvi",
        "image/x-eps",
        "image/vnd.djvu+multipage"
    ],
    "Picture": [
        "application/vnd.oasis.opendocument.image",
        "application/x-krita",
        "image/bmp",
        "image/cgm",
        "image/gif",
        "image/jpeg",
        "image/jpeg2000",
        "image/png",
        "image/svg+xml",
        "image/tiff",
        "image/x-compressed-xcf",
        "image/x-pcx",
        "image/x-photo-cd",
        "image/x-psd",
        "image/x-tga",
        "image/x-xcf"
    ],
    "Presentation": [
        "application/vnd.ms-powerpoint",
        "application/vnd.sun.xml.impress",
        "application/vnd.oasis.opendocument.presentation",
        "application/x-magicpoint",
        "application/x-kpresenter",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    ],
    "Spreadsheet": [
        "application/vnd.lotus-1-2-3",
        "application/vnd.ms-excel",
        "application/vnd.stardivision.calc",
        "application/vnd.sun.xml.calc",
        "application/vnd.oasis.opendocument.spreadsheet",
        "application/x-applix-spreadsheet",
        "application/x-gnumeric",
        "application/x-kspread",
        "application/x-kspread-crypt",
        "application/x-quattropro",
        "application/x-sc",
        "application/x-siag",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    ],
    "Text File": [
        "text/plain",
        "text/markdown"
    ],
    "Video": [
        "video/mp4",
        "video/3gpp",
        "video/mpeg",
        "video/quicktime",
        "video/vivo",
        "video/x-avi",
        "video/x-mng",
        "video/x-ms-asf",
        "video/x-ms-wmv",
        "video/x-msvideo",
        "video/x-nsv",
        "video/x-real-video"
    ]
}
```
</details>

I think we can do better though. Many of the mimetypes make sense; we can probably abstract some by searching the beginning of the mimetype string; for example, these match

Picture: `^image/`
Video: `^video/`
Music: `^audio/`

The easiest is probably just matching the first part of the mimetype in a first pass and extend it later.

**Comment by briansmith0** [comment]
For file types that the web browser can display (such as images), will the user be able to double click on the file to display it in the web browser?

**Comment by garrett** [comment]
@briansmith0 That makes sense! We were talking about a "preview" in Matrix last week. That could make sense for all types that can be previewed, as images. Like huge text documents, we'd need to make sure huge images would be handled in a special way.

We do have this sidebar (that still needs work); perhaps we could do something there (instead of a modal).

I'm not sure if we want to support thumbnailing of images in place of icons, however. We'd need to have some kind of thumbnailer background process and a cache for the thumbnails, which implies a way to clear the cache, and so on. (There's [an XDG spec for thumbnailing](https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html)... we wouldn't want to reinvent the wheel.) I think it _could_ in the future, but there's a lot of implied complexity, including security concerns when dealing with images. GNOME, for example, [runs all its thumbnailers in a sandbox](https://www.hadess.net/2017/07/security-for-security-gods-sandboxing.html), and that's helped prevent security issues already.

(Image security issues have been a method for jailbreaking locked down devices, which has been nice for things like game consoles and ebook readers. But they can also be used for nefarious things too, which we want to prevent.)

So having arbitrary graphical images read and converted on the server and sent to the browser _can_ be problematic, and we should guard against that, both for image previewing, but also especially for thumbnailing (as that can run in the background on a directory view, even without selecting an image).

For the time being, we're just going with a small set of icons, as mentioned in this issue. We should track any possible future image previewing as a separate issue and also thumbnailing as another issue (related to the first of image previewing, although it's even more complicated to implement properly).
