### ISSUE TITLE
As non-admin you can't chown to another user

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#393]
![image](https://github.com/cockpit-project/cockpit-files/assets/67428/ba8c41e7-87d2-4b47-9278-5742d807c9bc)

We should not shown this option if you aren't superuser.

**Comment by allisonkarlitskaya** [comment]
I wonder if there's some polkit API we can hit to do this...

**Comment by martinpitt** [comment]
See https://github.com/cockpit-project/cockpit/issues/11033 and https://github.com/cockpit-project/cockpit/pull/20283 - in general, predicting this with polkit is difficult :cry:

**Comment by jelly** [comment]
I would like to replicate the behavior of polkit as likely happens in `gnome-files` but for the first version I think it is more realistic to hide this option.

**Comment by jelly** [comment]
Using polkit implies using `pkexec` or do we ship our own rules?

I can't get pkexec to do work for me, while this works fine in a normal GNOME session.
```
[admin@fedora-40-127-0-0-2-2201 ~]$ pkexec
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/bin/bash' as the super user
Multiple identities can be used for authentication:
 1.  Administrator (admin)
 2.  fedora Cloud User (fedora)
Choose identity to authenticate as (1-2): 1
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
```

**Comment by jelly** [comment]
The bug was fixed, but leaving this open if we want to do a polkit like solution.
