### ISSUE TITLE
Publish a copr repo like podman

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#394]
Can be used for user testing and later reverse dependency testing with Cockpit.

**Comment by jelly** [comment]
@martinpitt can you add `cockpit-files` here https://github.com/cockpit-project/cockpit-files/runs/24212537652

I don't have admin privileges on our copr.

**Comment by martinpitt** [comment]
@jelly Whoops! Done (all our other projects are already there)

**Comment by jelly** [comment]
Thanks!
