### ISSUE TITLE
Crash when editing permissions of directory

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit-files#395]
Steps to reproduce: 

- Create a new directory
- Go in to that directory
- Click on the dots next to the directory name, and click "Edit permissions" (see screenshot below)
- Cockpit reports "Ooops!"

![directory](https://github.com/cockpit-project/cockpit-files/assets/60192516/b9bbfe73-80a9-4257-b8ca-248649e4e1ec)

**Comment by jelly** [comment]
This requires some state cleanup and making `cwdInfo` available anywhere and even if it works I noticed this whole dialog has a ton of other bugs.

The list of users is not alphabetically sorted
![image](https://github.com/cockpit-project/cockpit-files/assets/67428/c4e2dfec-a5cc-4220-9c05-5fddc6406c9c)


bin is not owned by `admin`, but by `root`:

![image](https://github.com/cockpit-project/cockpit-files/assets/67428/3cdf6d25-a6bd-403e-8915-ad7f929f56d9)

We limit the selection of user/groups to the `/etc/login.defs` this might make sense for setting ownership/group permissions but certainly not for showing.

(Also if an admin can't chown a dir to say postgresql I feel this functionality is a bit useless)
