### ISSUE TITLE
Setup translations

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#402]
* [x] create cockpit-files-weblate repository in Cockpit @allisonkarlitskaya 
* [x] create cockpit-files project in Weblate itself (ask someone who can) https://docs.fedoraproject.org/en-US/localization/hosting/#_request_a_new_translation_project_on_fedora_weblate
* [x] setting up workflow https://github.com/cockpit-project/cockpit/blob/main/.github/workflows/weblate-sync-pot.yml 
* [x] setting up workflow https://github.com/cockpit-project/cockpit/blob/main/.github/workflows/weblate-sync-po.yml

**Comment by jelly** [comment]
@allisonkarlitskaya can you create a repository on the cockpit organisation https://github.com/cockpit-project/cockpit-ostree-weblate

**Comment by martinpitt** [comment]
@jelly Done: https://github.com/cockpit-project/cockpit-files-weblate

**Comment by jelly** [comment]
Requesting a new project https://docs.fedoraproject.org/en-US/localization/hosting/#_request_a_new_translation_project_on_fedora_weblate

**Comment by jelly** [comment]
Requested a new project: https://pagure.io/fedora-l10n/tickets/issue/37

**Comment by allisonkarlitskaya** [comment]
This is almost done:

 - https://translate.fedoraproject.org/projects/cockpit-files/
 - https://github.com/cockpit-project/cockpit-files-weblate/
 - https://github.com/cockpit-project/cockpit-files-weblate/commit/4931139dc74f1db2e363efc69079f0500b03d70e

But it looks like we didn't copy the weblate-sync-po workflow yet.  Let's do that tomorrow.
