### ISSUE TITLE
Add an option to 'open' currently selected directory in cockpit terminal

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-files#48]

**Comment by KKoukiou** [comment]
@MahmoudHamdy02 why this has a wontfix label?

**Comment by MahmoudHamdy02** [comment]
Currently, having an 'open in terminal' button would kill the cockpit terminal (even if it was still running a command). I don't think there is an easy fix for this. Other solutions (like multiple terminal tabs) require a lot of work in cockpit not navigator

**Comment by jelly** [comment]
Closing in favour of https://github.com/cockpit-project/cockpit-files/issues/464
