### ISSUE TITLE
Screen shifts when clicking on a directory name, resulting in a double click entering a different directory

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit-files#494]
At some screen sizes, clicking on a directory name causes the screen to shift, which can result in a double click entering a different directory. 

For example, if I double click on "test1" in this screenshot, I actually end up in the "Public" directory. 

![Screenshot from 2024-06-03 10-16-12](https://github.com/cockpit-project/cockpit-files/assets/60192516/9677a6cc-2d66-4fb6-b81f-b736e08ae772)

In the first click of the double click, the screen shifts to:

![Screenshot from 2024-06-03 10-18-36](https://github.com/cockpit-project/cockpit-files/assets/60192516/a724df3c-1cd7-4b35-8db4-5cbf795c2bc6)

This screen shift places my mouse pointer under "Public", and if I click a second time, I am placed in the Public directory.  During a normal double click this all happens fast and results you thinking you are in the directory you started the double click on ("test1") when you actually ended up in a different directory ("Public")

**Comment by allisonkarlitskaya** [comment]
Thanks for the report.

I've hit this as well.  I thought I'd even opened an issue about it already, but I can't find it.
