### ISSUE TITLE
Scrollbar position is wrong when browsing /bin

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#496]
When scrolling a listing or icon view table the scrollbar is not inside the view.

![image](https://github.com/cockpit-project/cockpit-files/assets/67428/da0c5d5c-4044-44dc-80bc-bc6f6fb5e1ad)

**Comment by jelly** [comment]
And for the listview the `thead` should be sticky:

![image](https://github.com/cockpit-project/cockpit-files/assets/67428/a71400da-8275-412f-934f-5a9f238bfa7f)

**Comment by garrett** [comment]
#506 fixes this by reworking the layout, which includes moving the scrollbar to the content area instead of the page. It also enables a sticky header for the listview's thead (and fixes the sidebar shifting, but that's another issue that's being solved :wink:).
