### ISSUE TITLE
Browsing to the /tmp directory results in a crash

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit-files#507]
Using the latest version pulled from earlier today, if I browse to the /tmp directory there is a crash ("Ooops!" in upper right).  This was previously working with the version I pulled a couple of days ago.

**Comment by allisonkarlitskaya** [comment]
This is probably related to the content of something in your `/tmp` — I don't manage to reproduce it locally.  Can you show the contents of `ls -lF /tmp`?  Hopefully this has enough information to reproduce it...

**Comment by briansmith0** [comment]
I did some more testing, and it looks to be related to this socket file:

```
srwxrwxrwx. 1 gdm   gdm     0 Jun  4 06:56 dbus-tdt5lXSBHF
```

If I delete this file, the crash no longer occurs

**Comment by briansmith0** [comment]
Also seeing the  crash if I browse to /dev

**Comment by allisonkarlitskaya** [comment]
I can reproduce it.  It happens for any kind of special file (not a directory or file) and the cause is very obvious.
