### ISSUE TITLE
Bump cockpit depend to 318 ASAP

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-files#511]
We can drop some nastiness if we can depend on a newer cockpit.  Specifically, we need these:

 - https://github.com/cockpit-project/cockpit/commit/2a578f6cc12d4dae4f3b82c216324de68228c7b1
 - https://github.com/cockpit-project/cockpit/commit/b3de5f4bed87335bf120cbda3969bdd5cc06c004

**Comment by martinpitt** [comment]
I  take the liberty to move this to the "first version follow up" milestone. This doesn't have to block the first release IMHO. If you think otherwise, please slap my hand and move it back :grin:
