### ISSUE TITLE
Directory is empty (4 hidden files)

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-files#517]
The "Directory is empty" text is inaccurate when we're showing a directory that has hidden files.  We should add something to it, or reword it a bit in that case.

**Comment by Devanshuverma07** [comment]
Can you show some more details for this bug, so it will easy to understand and implement.

**Comment by jelly** [comment]
@garrett what do you think? Should we add `X hidden items` after `Directory is empty`?

**Comment by garrett** [comment]
If we're going to talk about it, then we should probably use an empty state pattern with an action to "fix" the problem. It'd look like this:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/f0d12b72-9165-40d8-983b-4b1843f5bf25)

And singular:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/0cab4e90-cdf5-4e01-8926-620aeecbd872)

Clicking on that action would change the "show hidden" state to true.

**Comment by allisonkarlitskaya** [comment]
I agree with "1 item is hidden" in singular but I'd argue that the text of the link should be "Show hidden items" even in the case where there's only one hidden item.  We're effectively changing the global "show hidden files" setting when we click that.

**Comment by garrett** [comment]
> I agree with "1 item is hidden" in singular but I'd argue that the text of the link should be "Show hidden items" even in the case where there's only one hidden item. We're effectively changing the global "show hidden files" setting when we click that.

I agree. Good catch.
