### ISSUE TITLE
Bookmarks (including home as default)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#522]
We should have bookmarks, providing a way to quickly navigate to locations.

By default, it should include:

1. Home
2. Trash (when implemented; see #520)
3. A way to add and remove additional custom directories

It would be an action preceding the location (as it affects the location), which looks like this:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/31fad7b3-6747-4607-a2e4-23111ec54f02)

When clicking, it shows a menu with items like so:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/a31f237f-2e9a-40aa-bbb7-b90f51f717a8)

When the directory is bookmarked, it is a filled star. When the directory isn't bookmarked, it is an empty star.

Bookmarked locations are "saved" into browser storage.

**Comment by subhoghoshX** [comment]
I think the "Add bookmark" label is a bit confusing. I almost thought it would open a new dialog. Something like "Add to bookmarks" (similar to Nautilus) may be better.

**Comment by garrett** [comment]
@subhoghoshX, Would "Bookmark current directory" make more sense to you? Along with "Remove current directory"?
