### ISSUE TITLE
Meaningless size label shown for folders

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-files#531]
Folders gets a "0 B" added under them, which isn't at all helpful.  I assume that's the `st_size` which is reported as 0 by btrfs.  Other filesystems might report something different there, but it's never going to be interesting to the user.

**Comment by jelly** [comment]
We should report something however, Nautilus shows the amount of files/directories in the directory

**Comment by allisonkarlitskaya** [comment]
> We should report something however, Nautilus shows the amount of files/directories in the directory

We can't easily report this.  We might add support to fsinfo, but it would increase the overhead...
