### ISSUE TITLE
Any chance to get an EPEL build in @cockpit/cockpit-preview?

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit-files#561]
Doesn't hurt to ask, but that would make it easier at least for me to consume the previews.

Thanks

**Comment by martinpitt** [comment]
Indeed, thanks @leomoty for the reminder! I sent #562

**Comment by martinpitt** [comment]
I added cockpit-files to the allowed packit forges in https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/
