### ISSUE TITLE
Details view: Permissions

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#565]
For showing permissions, I think the only thing that makes sense is to have the descriptive form with triplet attributes (not octal), and have descriptions for it in a tooltip to make it more approachable, like this:

![permissions in details, with a tooltip](https://github.com/cockpit-project/cockpit-files/assets/10246/67bdf803-ce6b-4d2b-86f9-dba7acac10f7)

Note the spacing, lack of `d` (as we have another place to show if it's a directory or file`), and grouping. The tooltip has alignment on the labels and for the content, so the content aligns (and isn't ragged due to being all in one line).

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit-files/issues/564#issuecomment-2175679284_

**Comment by jelly** [comment]
As we can sort on this column, we need some text for the filter dropdown:

![image](https://github.com/cockpit-project/cockpit-files/assets/67428/eb3b4424-069e-49a3-b834-f79a9a5c9f19)

Or do we leave it out of this dropdown?

**Comment by allisonkarlitskaya** [comment]
Sorting on permissions seems pretty marginal.

Copying from https://github.com/cockpit-project/cockpit-files/issues/564#issuecomment-2175733593 :+1: 

Please make sure to support `s` (`+xs`), `S` (`+s-x`) and `t`/`T` (sticky) in the output for permissions.

**Comment by jelly** [comment]
> Sorting on permissions seems pretty marginal.

Marginal? If you mean not important, sure, but as nautilus allows it, it seems like something we should do as well.

**Comment by garrett** [comment]
Nautilus allows it from the headers, but doesn't have it in the menu.

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/05a8ff47-98de-43c2-9972-42384be5ffe1)

We're trying to balance 3 different factors when it comes to sorting the table:

1. Permissions (and ownership) on a multi-user system are more important compared to a single-user desktop, so we shouldn't do a 1:1 duplication of desktop file manager features without thinking about it further.
2. [Cognitive overload](https://en.wikipedia.org/wiki/Cognitive_load) (aka: "mental workload" / "info paralysis" / "paradox of choice"): having too many items in the sort list will make it harder to find what people are looking for.
3. View compatibility: sorting options in the list need to make sense for both icon view and details view. Sorting by permissions isn't an obvious sorting order in icon view (it will look random).

Item 1 says it makes sense and can even be important on a server to sort by permission. Items 2 and 3 say adding it to the list will make that too cluttered, especially for the icon view. This is probably why Nautilus does not show permissions by default (due to 2 and 3, but also due to 1 as a single-user desktop system will generally own all the files themselves) and even when Nautilus is told to include permissions in the view, it does not add it to the menu (as that would be cluttered and not support both view modes).

---

On the other hand, KDE's Dolphin has these sorting options and much more. But it gets weird, as you can't see the sorting in the default view (icons) when you select it, and the menu structure is a mess. KDE often will add features just because it can, so I don't think it's a good standard to compare to.

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/a5e60a7c-462e-4286-935f-deb02540d0e5)

---

Windows is weird (sometimes the menu is there, sometimes it isn't) and doesn't have permissions:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/91478968-98b8-49b0-99a2-64632ff483e3)

But Windows also has a plethora of mostly-redundant view options (with even more hidden in Windows 3.1-style dialogs in the ... menu under "Properties" _and_ "Options"):

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/cc9f54ea-7c27-4cdd-a725-2b41b7f0171a)

And Windows has _2 context menus_, both with different options from the rest of the UI:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/04386cc9-5651-4cf3-86ac-a8f15aa86332)

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/20b248b0-1bcf-46cd-8414-081fa5dfdf78)

(The second one is triggered by selecting "More options" from the first.)

---

macOS Finder does sorting a little different. There's a menu in the headerbar that has various options, and when you select one other than the name (which just sorts by name), it _groups_ the items with sticky headers:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/742b4e64-56c8-4011-a483-f77671bdd2b8)

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/edd295cb-019b-41d4-9d5a-b929e33a4971)

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/64fb86a9-f0ca-412e-aba3-f4d536cb74a4)

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/9dd49f79-ee75-41e3-a624-f02247959a86)

But it gets a little wacky, as they have this duplicated in a ... menu that changes based on sort, what you have selected, and everything. Here's what it looks like with _lots of options_:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/017d23ba-c092-4a63-957d-71ceb9a605eb)

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/e8aab58c-286e-4876-a568-a7c4e78f42eb)

Same, but something's selected: 

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/1e0f9604-7767-4a85-a021-0297899d655e)

And then they have a "show view options" dialog that has many of the same settings, but even more to adjust the padding, spacing, font size, background wallpaper image (for the folder!), and so on, and that can be specific to the folder but also apply anywhere:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/96a33e9f-205a-4d14-ae36-b5cfe114bd53)

---

Anyway, looping back to the topic at hand:

- We definitely should have permissions as a sortable header.
- Even setting cognative overload aside, having the sort and icon view is odd, right?
- Only KDE has permissions; it's not in the view of other file managers (except Nautilus, but there it's opt-in for details view only)

And, more in depth (overall), but still applies here:

- We _can't be more absurd_ than Windows, macOS, or KDE unless we spend literal decades shoving new features in multiple places and never reevaluating things or tried our hardest to be weird.
- GNOME has iterated on the Nautilus UI and shuffled things around after thinking, so it's a pretty good reference, but isn't perfect.
- All of these examples are mainly for desktop UIs. Windows does have a multi-user server version, however; but I don't know if the UI is different for it.

**Comment by garrett** [comment]
Here's the most recent mockup for a list view:

![details mockups](https://github.com/cockpit-project/cockpit-files/assets/10246/eda147d9-904a-453a-adb1-d51de79f675f)

It's not easy to have divider lines in Penpot, so I haven't added them yet. (It's possible, but requires workarounds.) Therefore, ignore the lack of it. We can decide if we want divider lines still or not. The lack of lines isn't intentional.
