### ISSUE TITLE
Investigate reimplementing Back/Forward button navigation using pushstate

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-files#61]
https://developer.mozilla.org/en-US/docs/Web/API/History/pushState

**Comment by jelly** [comment]
@allisonkarlitskaya I think this is done now via `cockpit.location`?

**Comment by allisonkarlitskaya** [comment]
Didn't we drop the buttons entirely?

**Comment by jelly** [comment]
Indeed we did :)
