### ISSUE TITLE
Introduce file viewer for plaintext files

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-files#63]
Introduce a file viewer for code files (like plaintext, but with syntax highlighting)

Bonus item: (can be split into new issue if hard) edit text files?
Use https://www.patternfly.org/v4/components/code-editor

**Comment by ashutosh7i** [comment]
hello @KKoukiou ,
is this still open?

i would like to work on it and add a code/text preview thing as i am comfortable with patternfly and worked with it before.

**Comment by garrett** [comment]
I remember some discussion about this somewhere, but can't find it.

There were issues with the PatternFly code editor widget. I don't know of all the details. But the most basic first pass would be something like this:

![image](https://github.com/cockpit-project/cockpit-files/assets/10246/f0a51bfa-659b-481d-a540-e6cd2af762cb)

It uses a basic textarea (HTML, but probably PatternFly's wrapper to the HTML element). It is a modal so you don't lose your place in the file browsing and can edit one file after another. On the left is editing mode; on the right is view-only / read-only.

First pass could be read-only viewing. Second pass could be editing. Third pass could be some kind of code viewer enhancement. However, the goal should be quick and easy simple editing of plain text files only, not a full-blown IDE (or even a full text editor like vim or emacs), so stopping at pass 2 (editable text area), at least for a while, is fine.

**Comment by jelly** [comment]
This has been implemented in the basic editor PR.
