### ISSUE TITLE
pathbar: Edit should not be inside the pathbar widget

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#640]
The edit button is currently inside the pathbar. It should be outside of the pathbar and the pathbar should just contain path widgetry.

**Comment by jelly** [comment]
I don't fully understand what the pathbar widget is? The edit button is inside a `PageBreadCrumb` which honestly seems fine.

**Comment by garrett** [comment]
In other words: "Edit button should not be inside the breadcrumbs component".

It's _not fine_, unless the edit button is a location you go to that's above the top of the filesystem @ `/`.

**Comment by jelly** [comment]
Note that I talk about a `PageBreadCrumb` ie. [this](https://www.patternfly.org/components/page#pagebreadcrumb) which is basically a bar which spawns the full width. So you are saying we should use another bar like [this](https://www.patternfly.org/components/page#pagenavigation) and wrap PageBreadCrumb inside that? And then likely hack around in css?
