### ISSUE TITLE
pathbar: Use links for the links to directories, not buttons

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit-files#641]
Currently, the pathbar uses buttons. PatternFly has a whole lot of CSS around buttons, including wrapping, alignment, and other things. 

As these go places, they should be links. That should also not have a bunch of button-based assumptions, so links should also naturally improve the layout without having to override a lot of PF CSS.

Even [PatternFly's breadcrumbs](https://www.patternfly.org/components/breadcrumb/) (which are different as they use > icons as separators instead of / like a Linux filesystem) uses links.

**Comment by garrett** [comment]
Note, when reworking the pathbar, we should take care to address the accessibility concerns @ https://www.patternfly.org/components/breadcrumb/accessibility

**Comment by jelly** [comment]
The Breadcrumb component does not allow for specifying a different component to be the separator so we can't replace `>` with `/` easily.

**Comment by jelly** [comment]
```
<ul class="breadcrumbs">
  <li><a href="#/">system</a></li>
  <li>/</li>
  <li><a href="#/home/">home</a></li>
  <li>/</li>
  <li><a href="#/home/me/">me</a></li>
  <li>/</li>
  <li><span class="current">downloads</span></li>
  <li>/</li>
</ul>
```

**Comment by garrett** [comment]
It could be some React like this snippet, I guess:

```jsx
const FilesBreadcrumbs = ({ items }) => {
  const URIprefix = '/files#/?path=';

  const getFullPath = (index) => `/${items.slice(0, index + 1).join('/')}`;

  const handleBreadcrumbClick = (event) => {
    const { target, button, ctrlKey, metaKey } = event;
    const isAnchor = target.matches('a[data-location]');

    // Let the browser natively handle non-primary click events 
    // or if the control or meta (Mac) keys are pressed
    // ...this lets opening in a new tab or window work by default.
    if (isAnchor && (button !== 0 || ctrlKey || metaKey)) {
      event.preventDefault();
      // Replace the console.log with cockpit.go() or whatever Files uses.
      console.log('Go to:', target.getAttribute('data-location'));
    }
  };

  return (
    <nav aria-label="Breadcrumb list" className="files-breadcrumbs" role="navigation">
      <ol onClick={handleBreadcrumbClick}>
        <li>
          <a href={`${URIprefix}/`} data-location="/">System</a>
        </li>
        {items.map((item, index) => (
          <li key={index}>
            {index < items.length ? (
             <a
                href={`${URIprefix}${encodeURI(getFullPath(index))}`}
                data-location={getFullPath(index)}
              >
                {item}
              </a>
            ) : (
               <span className="current">{item}</span>
            )}
          </li>
        ))}
      </ol>
    </nav>
  );
};
```

I might've made typos or "thinkos" while writing this. It's to give you the general idea. I haven't tested this, but it should probably be close to working (as it's pretty straightforward). :wink: 

I figured we should wrap it in a [nav element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav) (as you're navigating) and use ordered list  instead of unordered (as it's inherently in an order). I also let the mouse, control, and command (for Mac) keys pass through so the links are treated like links and open up a new tap/window in the browser using the href attribute (instead of handling that ourselves in JS).

Then you could use it like so, with a basic list of paths:

```jsx
const breadcrumbItems = ['home', 'garrett', 'Projects', 'Cockpit'];
<FilesBreadcrumbs items={breadcrumbItems} />
```

The list of paths  could even be `'/home/foo/bar'.split('/')`, I suppose.

With some basic CSS like this, which specifies the layout and spacing, and adds a visual `/` in the CSS so you don't have to in the JSX:

```scss
.files-breadcrumbs {
  > ol {
    display: inline-flex;
    list-style: none;
    gap: var(--pf-v5-l-flex--spacer--sm);
  }

  li:not(:last-child)::after {
    content: '/';
    color: var(--pf-v5-l-flex--spacer--sm);
    margin-inline-start: 0.5em;
  }
}
```

PatternFly should ideally handle the rest of the styling. (The color should only style the /, whereas PF will probably style the links appropriately.)

**Comment by garrett** [comment]
Actually, nevermind.

:facepalm: 

We can just use the PatternFly breadcrumbs as-is and add this little CSS override:

```css
.pf-v5-c-breadcrumb__item-divider > .fa-angle-right::after {
  content: "/";
  color: var(--pf-v5-global--Color--200);
}
```

That's the simplest solution.
