### ISSUE TITLE
Files not showing after manual install on ClearLinux (as there's no bundles for the applications)

### ISSUE THREAD

**Issue by ThaDaVos** [cockpit-project/cockpit-files#649]
To install it on my ClearLinux box, I did the same as I did with installing `cockpit-machines` - as based on the make-file, except I placed it in `/usr/share/cockpit` instead of `/usr/local/share/cockpit` as the latter doesn't exist:
1. I downloaded the latest release tar with wget
2. extracted it into a folder in my home directory `/home/{user}/modules/cockpit-files`
3. Went into `/usr/share/cockpit`
4. Created a symbolic link `sudo ln -s /home/{user}/modules/cockpit-files/dist files`
5. Went into `/usr/share/metainfo
6. Created a symbolic link `sudo ln -s /home/{user}/modules/cockpit-files/org.cockpit-project.files.metainfo.xml org.cockpit-project.files.metainfo.xml`

But for some reason it won't show itself in my Cockpit Panel - while `cockpit-machines` does show (as `Virtuele Machines`):
![afbeelding](https://github.com/user-attachments/assets/c592f88b-ad8d-4179-a33b-32818e5ae4de)

**Comment by ThaDaVos** [comment]
Okay, I now created the `/usr/local/share/cockpit` folder and moved both symlinks to there - but `cockpit-machines` still works but `cockpit-files` does not

**Comment by martinpitt** [comment]
Can you please check `cockpit-bridge --packages`? What does `ls -l /usr/local/share/cockpit/files/` say? It should have the `manifest.json` and the usual *.html, *.js, *.css files.

**Comment by ThaDaVos** [comment]
Thanks for the hint to check `cockpit-bridge --packages` it shows the following:
```Shell
cockpit.packages-WARNING: /usr/local/share/cockpit/files/manifest.json required cockpit version (318) not met
base1                                                         /usr/share/cockpit/base1
machines             Virtual machines                         /usr/local/share/cockpit/machines
metrics                                                       /usr/share/cockpit/metrics
network              Networking                               /usr/share/cockpit/networkmanager
shell                                                         /usr/share/cockpit/shell
sosreport            Diagnostic reports                       /usr/share/cockpit/sosreport
static                                                        /usr/share/cockpit/static
system               Overview, Services, Logs, Terminal       /usr/share/cockpit/systemd
users                Accounts                                 /usr/share/cockpit/users
```

See first line - it's due to a version not being met - according to `cockpit-bridge --version` i am on 314:
```Shell
Version: 314
Protocol: 1
```

**Comment by ThaDaVos** [comment]
I changed the requirement from `318` to `314` in the manifest - it shows and seems to work - are there any downsides to this?

**Comment by martinpitt** [comment]
It requires version 318 for quite a lot of things -- showing file information (size, permissions, etc.), and I think also uploading files to the server.

So yes, to use it properly you should upgrade cockpit to the latest version. Mystery solved!
