### ISSUE TITLE
Filtering a large directory is janky

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-files#669]
Open a large directory like `/bin` and start typing. There's a significant delay in the characters appearing or disappearing when you type or press backspace.

**Comment by subhoghoshX** [comment]
My initial intuition is to use [useDefferedValue()](https://react.dev/reference/react/useDeferredValue). I'll try to look into it.

**Comment by garrett** [comment]
Shouldn't you just do standard debounce on the input?
