### ISSUE TITLE
translation: add "zh_TW" language to Weblate

### ISSUE THREAD

**Issue by xilwen** [cockpit-project/cockpit-files#671]
I want to contribute translations for `Chinese (Traditional) (zh_TW)`,  
but I run into following message in Weblate:
```
Start new translation
===
Please choose the language you want to translate to. A translation file will be created based on files.pot with all strings untranslated.

Language
---Please Choose---

This list includes only basic languages. Please contact project maintainers to add others.
```

That "Please Choose" list does not contain zh_TW, which exists in `cockpit` repository.  
Could you please add `zh_TW` language?  

Thanks.

**Comment by martinpitt** [comment]
Of course, thanks for your interest! Created: https://translate.fedoraproject.org/projects/cockpit-files/cockpit-files/zh_TW/
