### ISSUE TITLE
Wrong select menu background color

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#683]
Differs from the other button:

![image](https://github.com/user-attachments/assets/4826e20e-985e-4424-b3da-e8b068cc79cd)

**Comment by garrett** [comment]
This screenshot also doesn't have the alignment fix of `align-items: middle` I mentioned yesterday in matrix and in the breadcrumbs PR, which shouldn't be necessary (and isn't needed in Firefox), but it apparently is in Chrome.

**Comment by jelly** [comment]
Once more:

![image](https://github.com/user-attachments/assets/416539f7-5195-4cb0-aa84-96a778f2fa0f)

**Comment by garrett** [comment]
Expected: Buttons should have the same background color. In light mode, that's the same as the background, and in dark, they should be the same as each other. Making the bookmarks the same as the edit button seems reasonable to me, as the lighter background is less contrast and not consistent with the light mode.
