### ISSUE TITLE
Somehow the build process stupidly tries to use linux-x64 flavour of esbuild on a Raspberry Pi 3B+, so it fails.

### ISSUE THREAD

**Issue by rwperrott** [cockpit-project/cockpit-files#705]
I tried to build this, as per the readme.md instructions, in my case on a Raspberry Pi 3B+ with a fresh install of [2024-07-04-raspios-bookworm-arm64](https://downloads.raspberrypi.com/raspios_arm64/images/raspios_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64.img.xz) on it, but somehow it keeps picking the wrong kind of `esbuild`, `linux-x64` rather than `linux-amd64`, so the build fails. I tried all the suggestions in the long fail message, but none worked.

I don't need this node.js glitch hassle, so am using the latest deb for https://github.com/45Drives/cockpit-navigator on both my Raspberry Pi (arm64) and my Debian bookworm PCs, because it just works, including user/group changes and cut & paste of files.

**Comment by martinpitt** [comment]
I suppose you meant `linux-arm64`, not `-amd64`? we actually do ship the -wasm variant for building on non-x86 architectures, but esbuild somehow doesn't like that. You need to `rm -r node_modules; npm install` before building to work around that.

Alternatively: You can totally build this deb on x86 and then use it on ARM -- it's `Archtitecture: all`.

I [uploaded cockpit-files to Debian one month ago](https://ftp-master.debian.org/new.html), and I hope that at some point it will be reviewed/accepted -- then it can be installed as a normal deb.

Sorry for the inconvenience!

**Comment by allisonkarlitskaya** [comment]
This is a known issue (which you might have searched for → #609) and GitHub isn't a forum for obnoxious ranting.
