### ISSUE TITLE
cockpit-files install by default

### ISSUE THREAD

**Issue by Patrick-1-1-1-PH** [cockpit-project/cockpit-files#767]
cockpit-files is awesome and can we have it installed with the cockpit main app already?

**Comment by jelly** [comment]
It is always going to be a separate plugin and not part of cockpit itself. This allows us to more easily develop it and push updates.

**Comment by leomoty** [comment]
Also you can find in `Tools > Applications` inside your cockpit instance, so discoverability shouldn't be a big problem either.
