### ISSUE TITLE
File Manager download does not work for additional hosts

### ISSUE THREAD

**Issue by jontylovell** [cockpit-project/cockpit-files#773]
The cockpit-files feature is great and works on several difference hardware platforms. However, if a cockpit server is configured with several additional hosts and those hosts have cockpit-files installed then it is possible to browse the file system, but not to download files from the remote host. The download is initiated but a zero byte file is returned. The issue appears to be that the file download is initiated, but there is no pass-through of data from the client host to the server host that is running the cockpit web interface.

**Comment by mac2net** [comment]
This is also a problem with cockpit-navigator.
