### ISSUE TITLE
File downloads not working with host switcher

### ISSUE THREAD

**Issue by marvinruder** [cockpit-project/cockpit-files#781]
Given that I logged onto the Cockpit web interface on a primary server, used the host switcher to connect to a secondary server and opened the File Browser on the secondary server,

- when I attempt to download a file from a path under which also a file on the primary server exists, then the file from the primary server is downloaded,
- when I attempt to download a file from a path under which no file on the primary server exists, then an empty file is downloaded.

**Comment by martinpitt** [comment]
Duplicate of #773. The fix just landed, if you use Fedora or CentOS, you can get a package built from the main branch from https://copr.fedorainfracloud.org/coprs/g/cockpit/main-builds/build/8132461/
