### ISSUE TITLE
Editor filename should not be the full path

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-files#790]
Currently we show the full path, @garrett mentioned this should just be the "filename"

![image](https://github.com/user-attachments/assets/37e657a9-255d-48fa-9adb-0fe193c725fc)

**Comment by jelly** [comment]
@garrett please confirm.

**Comment by garrett** [comment]
Agreed. You're already in the directory; I don't think we need the full path. The full path also pushes the filename out of the way, especially on deep paths.
