### ISSUE TITLE
Spanish and portuguese translation

### ISSUE THREAD

**Issue by rickygzz** [cockpit-project/cockpit-files#884]
I translated the string for Spanish and Portuguese in https://translate.fedoraproject.org/projects/cockpit-files/cockpit-files/

Could somebody help me to import them into this project?

**Comment by martinpitt** [comment]
Gracias @rickygzz ! This will happen automatically through https://github.com/cockpit-project/cockpit-files/actions/workflows/weblate-sync-po.yml. Last night's run didn't yet pick them up, but the next one will.
